[project]
name = "hello-ci-cd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["uv"]
build-backend = "uv.build"

[tool.uv]
python-preference = "only-managed"

[tool.uv.extra-build-dependencies]
hello-ci-cd = ["uv.build"]

[tool.uv.dependencies]
pytest = "*"
