[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "hello-ci-cd"
version = "0.1.0"
description = "A small project for CI/CD testing"
readme = "README.md"
requires-python = ">=3.11"

[tool.uv]
python-preference = "only-managed"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
