name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install UV
        run: |
          curl -sSf https://install.urschrei.dev/uv.sh | sh
          export PATH="$HOME/.uv/bin:$PATH"
          uv --version

      - name: Run tests
        run: |
          export PATH="$HOME/.uv/bin:$PATH"
          PYTHONPATH=. uv run pytest tests

